#!/bin/sh

# init.d script

# Shortened options for better readability
# --start = -S
# --stop = -K
# --exec = -a

NAME=aesdsocket
DAEMON=/usr/bin/${NAME}

case "$1" in
    start)
        echo "Starting aesdsocket..."
        start-stop-daemon --start --name $NAME --exec $DAEMON -- -d
        echo "aesdsocket started."
        ;;
    stop)
        echo "Stopping aesdsocket..."
        start-stop-daemon --stop --name $NAME
        echo "aesdsocket stopped."
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
